# Generated by Django 3.2.9 on 2021-11-20 19:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import server.base.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Loots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('attributes', models.JSONField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=server.base.services.get_path_upload_avatar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), server.base.services.validate_size_image])),
            ],
        ),
        migrations.CreateModel(
            name='LngDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('meta_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('meta_description', models.CharField(max_length=150)),
                ('keyboards', models.CharField(max_length=200)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loots.languageall')),
                ('loots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loots.loots')),
            ],
        ),
        migrations.CreateModel(
            name='BettingsLoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bettings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettings.bettings')),
                ('loots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loots.loots')),
            ],
        ),
    ]
